server:
  port: 9094

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: NOTIFICATIONS
      auto-index-creation: true

  mail:
    host: ${HOST_MAIL}
    port: 587
    username: ${APP_USERNAME}
    password: ${APP_PASSWORD}
    email: ${FROM_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL} 