server:
  port: 9094

spring:
  application:
    name: notification-service

# Using local db for development purposes
  data:
    mongodb:
      uri: mongodb://localhost:27017/NOTIFICATION

  mail:
    host: ${HOST_MAIL}
    port: 587
    username: ${APP_USERNAME}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL} 