server:
  port: 9094

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: ${NOTIFICATIONS_SERVICE_MONGODB_URI}
      database: NOTIFICATIONS
      auto-index-creation: true

  mail:
    host: ${NOTIFICATIONS_SERVICE_HOST_MAIL}
    port: 587
    username: ${NOTIFICATIONS_SERVICE_APP_USERNAME}
    password: ${NOTIFICATIONS_SERVICE_APP_PASSWORD}
    email: ${NOTIFICATIONS_SERVICE_FROM_MAIL}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    